application:
  dataPath: ./data
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:lab4
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: /db/changelog/master.xml


