spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres?currentSchema=public
    username: postgres
    password: postgres
  liquibase:
    enabled: false
    change-log: /db/changelog/master.xml